### ISSUE TITLE
material browser issue

### ISSUE THREAD

**Issue by viquiuxd** [EnviralDesign/GeoPix#15]
**Describe the bug**
The selection of the material does not work with imported objects, I can only make it work with "primitives"

**To Reproduce**
Import geo, select any 3D file with .obj format created in some other CAD software
Select geo and in Geometry tap open material browser
Select some material for example "brick red 03"
the geo goes black

**Comment by EnviralDesign** [comment]
Your imported geometry probably didn't have uv's exported with it - this was causing some issues on the shader resulting in NaN's that end up making the object look black.

I've fixed these, now objects with no uv's will still look shaded when you apply a material, but they of course will not be properly texture mapped. you'll need to export it from your cad software with uvs for that to work right. GeoPix at this time doesn't do any uv generation for objects.

Just to be extra sure - can you try importing some of the example files that GeoPix has after the downloader runs first time? most if not all of those should have uv's and should work when you apply a material.

Thanks for the report!
