### ISSUE TITLE
Errors @Startup accumulating 

### ISSUE THREAD

**Issue by magicstreet** [EnviralDesign/GeoPix#21]
**Describe the bug**
just installed GP 2.0 a,d at startup of the app the Red bar shows errors acccumulating 
Impossible to create any thing in editor.

Appears straight at the Launch GP and errors start piling
![Capture d’écran 2021-05-11 111342](https://user-images.githubusercontent.com/84011938/117790798-fc4a0c00-b249-11eb-9e16-20863eda7f78.png)

**Error log :**
======= Newest Errors at the Top =======

SOURCE: DAT : 3 : /software/top/PixelMapEditor/Scheduler/chopexec_updateTime
ERROR: (300) Traceback (most recent call last):
  File "/software/top/PixelMapEditor/Scheduler/chopexec_updateTime", line 5, in whileOn
td.AttributeError: 'td.containerCOMP' object has no attribute 'GetCurrentTime_Epoch' Context:/software/top/PixelMapEditor/Scheduler

**When trying to create an object** 
![Capture d’écran 2021-05-11 111511](https://user-images.githubusercontent.com/84011938/117790998-2d2a4100-b24a-11eb-8603-df877fd247c4.png)
**Error log** 
======= Newest Errors at the Top =======

SOURCE: DAT : 3 : /software/top/PixelMapEditor/Viewport/UI_Overlay/Create_Dialogue/body/collection/buttonBank/Fixture/Template0/Gui/label/panelexec_doSomething
ERROR: (1) Traceback (most recent call last):
  File "/software/top/PixelMapEditor/Viewport/UI_Overlay/Create_Dialogue/body/collection/buttonBank/Fixture/Template0/Gui/label/panelexec_doSomething", line 9, in onOffToOn
td.Error: File "/software/top/PixelMapEditor/Viewport/UI_Overlay/Create_Dialogue/body/collection/buttonBank/Fixture/command", line 1
td.Error: Module compilation error. See /software/top/PixelMapEditor/logic/local/modules/create for details.
Results of run operation resulted in exception.

SOURCE: DAT : 3 : /software/top/PixelMapEditor/logic/local/modules/create
ERROR: (1) Traceback (most recent call last):
  File "/software/top/PixelMapEditor/logic/local/modules/create", line 2
    r = importDAT(args[0]);
td.Error: Module compilation error. See /software/top/PixelMapEditor/logic/local/modules/tdUtils for details.

SOURCE: DAT : 3 : /software/top/PixelMapEditor/logic/local/modules/tdUtils
ERROR: (1) Traceback (most recent call last):
  File "/software/top/PixelMapEditor/logic/local/modules/tdUtils", line 19
    r = previousimport(*args, **kw)
ModuleNotFoundError: No module named 'natsort'

SOURCE: DAT : 3 : /software/top/PixelMapEditor/Scheduler/chopexec_updateTime
ERROR: (297) Traceback (most recent call last):
  File "/software/top/PixelMapEditor/Scheduler/chopexec_updateTime", line 5, in whileOn
td.AttributeError: 'td.containerCOMP' object has no attribute 'GetCurrentTime_Epoch' Context:/software/top/PixelMapEditor/Scheduler

**Desktop (please complete the following information):**
 - OS: Windows 10 v. 19041.867
 - Browser Chrome

**Comment by EnviralDesign** [comment]
Hi, thanks for reporting.

Looks like some python modules are not being found, could be several reasons for this, but can you do the following:

1) start up GP again, so that it's creating those errors.
2) go to Tools -> Errors and Diagnostics.
3) go to the Python Diagnostics tab.
4) click "re-import Modules" at the top.

copy/paste or upload screenshot of results please.
It should look something like this modules are being found:

```
Could not remove developer system python path... skipping.
pyperclip was succesfully found!
netifaces was succesfully found!
natsort was succesfully found!
serial was succesfully found!
scipy was succesfully found!
sklearn was succesfully found!
humanize was succesfully found!


Python Paths:
C:\Program Files\Derivative\TouchDesigner.2021.12380\bin
C:\Program Files\Derivative\TouchDesigner.2021.12380\bin\python37.zip
C:\Program Files\Derivative\TouchDesigner.2021.12380\bin\DLLs
C:\Program Files\Derivative\TouchDesigner.2021.12380\bin\lib
C:\Program Files\Derivative\TouchDesigner.2021.12380\bin
C:\Program Files\Derivative\TouchDesigner.2021.12380\bin\lib\site-packages
C:/Program Files/Derivative/TouchDesigner.2021.12380/Config/Cmd
C:\Users\envir\Documents\GitHub\GeoPix\.py\Lib\site-packages
```

I am assuming some or all of the modules were not found. If that ends up being the case for you we can go from there to find out why.

**Comment by EnviralDesign** [comment]
A second thing to check, if you could - in your GeoPix root directory, there should be a folder called .py. Can you check the filesize on that and post a screenshot of the properties page here? Should match or be very close to this:
![image](https://user-images.githubusercontent.com/10091486/117915121-4531ad00-b2aa-11eb-83a2-398e5dd26374.png)

**Comment by magicstreet** [comment]
Hi Lucas,
Thanks for your feedback, it seems there was a problem when running the START_GEOPIX, I re-runned it and now seems to work fine. .py was not there and now is. Thanks will now get into GP! 
Thanks again for your incredible work 
Best

**Comment by EnviralDesign** [comment]
awesome thanks ! if you run into something again, try to copy out the *_Log.txt files in the root as they should yield something helpful on my end.
