### ISSUE TITLE
[Bug] Crashing after duplicating a parent

### ISSUE THREAD

**Issue by LimitlessGreen** [EnviralDesign/GeoPix#27]
# [Bug] Crashing after duplicating a parent

**Description**
GeoPix does crash after duplicating a parent.

**Steps to Reproduce**

1. Create two simple cubes
2. Select both and make one of them a parent
3. Try to duplicate the parent
4. **Crash**

`GeoPix Version: 2.0.15329`

I hope this helps to improve this nice piece of software :)

**Comment by EnviralDesign** [comment]
ah wow thanks for this! I have had this happen to me randomly but hadn't been able to recreate. Taking a look :)

**Comment by EnviralDesign** [comment]
ok tracked this down mostly ,and found a work around that ended up simplifying some other code as well.
fixed in 15334 and later

**Comment by LimitlessGreen** [comment]
Nice, thank you! :)
