### ISSUE TITLE
TouchDesigner Download Estimating 5+ Days to Download

### ISSUE THREAD

**Issue by IIAIronWolf** [EnviralDesign/GeoPix#32]
**Describe the bug**
After starting either the .bat file or the .exe (after downloading the repository .zip file from Github) the TouchDesigner download process is estimating 5+ days to download and staying at 0%.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A (but Chrome)

**Comment by IIAIronWolf** [comment]
Solution: Download directly from the TouchDesigner website.

**Comment by EnviralDesign** [comment]
Super weird! I wonder if this was temporary and they were doing some updates to their site or something. Just getting around to testing this out myself, but not able to reproduce this bug.

If you're able to try again, does it still do this for you?
