### ISSUE TITLE
Only the first cone emitter in custom fixtures gets rendered

### ISSUE THREAD

**Issue by cf1331** [EnviralDesign/GeoPix#34]
**Describe the bug**
Only the first cone emitter in custom fixtures gets rendered.

**To Reproduce**
See this [fixture profile](https://github.com/EnviralDesign/GeoPix/files/6832319/HY-2032A.zip). 

**Expected behavior**
If you can add multiple cone emitters to a fixture, then they should all be rendered. Fixtures exist that have multiple emitters and it would be useful to be able to visualize them.

**Screenshots**
![2021-07-17 GeoPix Fixture Cone Issue](https://user-images.githubusercontent.com/1275580/125984253-81621cfc-5e1b-4d9e-9be6-2b6b12b5bc04.JPG)
The green cone from the emitter on the right side of the fixture isn't visible.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 
**Additional context**
Just wanted to add thanks for releasing GeoPix. I've been trying it out over the past week and it's great!

**Comment by EnviralDesign** [comment]
Hey @cf1331 , thanks for writing about this - yeah you're absolute right there was a devious little bug that flew under the radar up until now preventing multi emitter custom fixtures from working properly. give it a go now, you should be good with latest but keep me posted if not!
