### ISSUE TITLE
Cannot move 3D view

### ISSUE THREAD

**Issue by gwh14** [EnviralDesign/GeoPix#44]
**Describe the bug**

Log current
======= Newest Errors at the Top =======
SOURCE: COMP : 3 : /UberGui/CustomFixtureEditor/container_Channels
ERROR: (1) TypeError: float() argument must be a string or a number, not 'NoneType'
Context:(Parameter: Offset)

SOURCE: COMP : 3 : /UberGui/UiMapper/Body/Drivers/driverMaps/driverPoolScrollable/container1_template
ERROR: (9) TypeError: float() argument must be a string or a number, not 'NoneType'
Context:(Parameter: Background Color)

**To Reproduce**
1.When I open the software, I can't remove the 3D view,I cannot zoom, move, rotate objects.
**Expected behavior**
![捕获](https://user-images.githubusercontent.com/54398986/130638863-c0c7874a-1abb-4c06-aa27-70edd7fe472c.PNG)

**Comment by EnviralDesign** [comment]
I haven't been able to recreate this issue. Do you see any python import errors in the Python Diagnostics?
![image](https://user-images.githubusercontent.com/10091486/130700024-d9f0b627-888f-44fc-97ea-60c2403d59e8.png)


Also, when you hold alt, and try to nav camera, do you see any new errors pop up in the System Errors tab? The two errors you linked should not relate to camera movement in the main Viewport.

**Comment by gwh14** [comment]
Thank you for your help.I found the problem,Because the  Network interception,when I install pythen Files,some files was installed failed that caused I can't move 3d view.At the same time,I have the another question that how to play the music in the movie.I want the lights to flash with the music, but I can't play music to the device. 
Here are some of my settings. I'm not sure if it's my settings. problem
.
![micro](https://user-images.githubusercontent.com/54398986/131252580-2815a317-7c2b-4323-bcd5-02b3bcf856a7.PNG)
![捕获](https://user-images.githubusercontent.com/54398986/131252584-28b850e4-4ee9-4f2e-87a9-557f07456d71.PNG)
![preference](https://user-images.githubusercontent.com/54398986/131252588-a0ee0d9c-5c15-468f-8584-d277c3fa9f31.PNG)

**Comment by EnviralDesign** [comment]
You are correct, there was a bug in the audio sampler from an earlier fix I made somewhere else. This has been fixed in the latest, thanks for the report!

**Comment by gwh14** [comment]
Your software is very creative. It solves many problems caused by my direct use of touchdesigner to design lights. In addition, I have a suggestion: geopix needs to download some Python files when it is started for the first time, but it is easy to fail due to the network firewall in some countries.I hope to provide the. Py folder directly in future updates, so as to avoid many hard to find errors.
