### ISSUE TITLE
Undo / CTRL-Z

### ISSUE THREAD

**Issue by jholmes09** [EnviralDesign/GeoPix#46]
There is currently no undo functionality of any kind.

I feel this is an important enhancement due to the granularity of parameters we are allowed and the fact that the scroll-wheel affects whichever parameter you are hovering over (even if you are moving the mouse in the process). There are many high-probability scenarios that you might accidentally overshoot a parameter or change something you did not mean to.

A quick CTRL-Z would be very helpful!

**Comment by EnviralDesign** [comment]
@jholmes09 There is actually an undo function in the Editor, however I haven't had it binded to ctrl+z yet. For whatever reason TD's internal ctrl+z I can't seem to bypass so when you ctrl+z you are potentially undoing things in the backend.

![image](https://user-images.githubusercontent.com/10091486/131679159-4efcdd2a-ad54-4258-afd9-b994aad31b1b.png)

This probably is harmless if you haven't been into the network and made changes but I don't want to bind it to that hotkey until that is fixed. Hopefully this helps for now! 

Undo is still not perfect mind you, so tread lightly. :) It's such a common thing, yet so difficult to implement robustly in TouchDesigner projects.
