### ISSUE TITLE
Can't fetch library assets

### ISSUE THREAD

**Issue by lepeitschke** [EnviralDesign/GeoPix#60]
**Describe the bug**
This bug appeared during the first installation of GeoPix. Following the instructions I've opened the windows batch file **START_GEOPIX.bat**. During the fetching of the library assets it was unable to download the files. In the log file I've seen that it show the following message: 
2)--Downloading files list from remote server----"
20 redirections exceeded.

Though, it opens up Geopix just fine afterwards.

**To Reproduce**
1. Go to 'GeoPix file Folder'
2. Click on 'START_GEOPIX.bat'
4. See the error during the BEGIN Library Fetch Script

**Expected behavior**
A download list of tiff- and obj-files should appear

**Screenshots**
Screenshot from command window during the installation process
![image](https://user-images.githubusercontent.com/120375184/207030734-d15f6e75-70f6-4e1f-acce-b0dea9bdd5e4.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [brave]
 - Version [GeoPix v2.0.15511 (2022-07-10) TD v2021.16410]

**Additional context**
Log-file stating that 20 redirections have been exceeded
[library_downloader_Log.txt](https://github.com/EnviralDesign/GeoPix/files/10207376/library_downloader_Log.txt)

**Comment by foong** [comment]
Having the same issue, seems like the url in the .bat script it not working anymore.

**Comment by EnviralDesign** [comment]
Hey thank you for the report, working on a fix for this

**Comment by EnviralDesign** [comment]
fixed! had some issues with my websites DNS name servers
