### ISSUE TITLE
Wget.exe does not run on windows 10 x64

### ISSUE THREAD

**Issue by secolaha** [EnviralDesign/GeoPix#9]
**Describe the bug**
when running the .BAT file I get an err or saying the the version of wget is incompatible with my computer.

running windows 10 prerelease 21354.1

**Comment by LimitlessGreen** [comment]
please download it via `https://github.com/EnviralDesign/GeoPix.git`

**Comment by LimitlessGreen** [comment]
Alright. I was able to reproduce it on an other PC.
I'll investigate this further

**Comment by secolaha** [comment]
I think curl.exe might be more portable.

**Comment by LimitlessGreen** [comment]
I know the reason: I cloned the repo without lfs installed. Install lfs and try it again https://git-lfs.github.com/

**Comment by EnviralDesign** [comment]
from my tests on my 3 laptops wget seemed to be good - but as @LimitlessGreen is saying it's prob the lfs and large file challenge I'm working through atm.

@secolaha Did you download via the green download code button in github? or the releases area on the right?

Either way have some time today again and going to finish sorting some things out.

**Comment by LimitlessGreen** [comment]
@secolaha Is the problem gone?
If so, we could close this issue.

**Comment by secolaha** [comment]
Yes it work! (allthough it tries to install a previous version of TD. Is this by design?)

**Comment by EnviralDesign** [comment]
That is yep. Thanks for the confirmation.
